on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job met demo-action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: demo action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Delsin Van Grembergen'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
